import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('en');
  const [languages, setLanguages] = useState([
    { code: 'en', name: 'English', flag: '🇺🇸' },
    { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
    { code: 'ta', name: 'தமிழ்', flag: '🇮🇳' }
  ]);

  // Load language preference from localStorage
  useEffect(() => {
    const savedLanguage = localStorage.getItem('preferredLanguage');
    if (savedLanguage && languages.find(lang => lang.code === savedLanguage)) {
      setCurrentLanguage(savedLanguage);
    }
  }, []);

  // Save language preference to localStorage
  const changeLanguage = (languageCode) => {
    if (languages.find(lang => lang.code === languageCode)) {
      setCurrentLanguage(languageCode);
      localStorage.setItem('preferredLanguage', languageCode);
    }
  };

  // Translation function for common UI text
  const t = (key) => {
    const translations = {
      en: {
        // Navigation
        'nav.home': 'Home',
        'nav.translate': 'Translate',
        'nav.chatbot': 'ChatBot',
        'nav.history': 'History',
        'nav.profile': 'Profile',
        'nav.about': 'About',
        'nav.doctor_tips': 'Doctor Tips',
        'nav.login': 'Login',
        'nav.signup': 'Sign Up',
        'nav.logout': 'Logout',
        
        // Authentication
        'auth.login_to_account': 'Login to your account',
        'auth.or': 'Or',
        'auth.already_have_account': 'Already have an account?',
        'auth.sign_in_here': 'Sign in here',
        'auth.username': 'Username',
        'auth.email': 'Email address',
        'auth.password': 'Password',
        'auth.confirm_password': 'Confirm Password',
        'auth.username_placeholder': 'Choose a username',
        'auth.email_placeholder': 'Enter your email',
        'auth.password_placeholder': 'Enter your password',
        'auth.confirm_password_placeholder': 'Confirm your password',
        'auth.signing_in': 'Signing in...',
        'auth.sign_in': 'Sign in',
        'auth.creating_account': 'Creating account...',
        'auth.create_account': 'Create account',
        'auth.back_to_home': '← Back to home',
        
        // Common
        'common.loading': 'Loading...',
        'common.error': 'Error',
        'common.success': 'Success',
        'common.save': 'Save',
        'common.cancel': 'Cancel',
        'common.delete': 'Delete',
        'common.edit': 'Edit',
        'common.close': 'Close',
        'common.confirm': 'Confirm',
        'common.language': 'Language',
        'common.speak': 'Speak',
        'common.stop': 'Stop',
        'common.translate': 'Translate',
        'common.clear': 'Clear',
        
        // Profile
        'profile.title': 'Profile Settings',
        'profile.subtitle': 'Manage your account and role preferences',
        'profile.username': 'Username',
        'profile.email': 'Email',
        'profile.role_patient': 'Patient',
        'profile.role_doctor': 'Doctor',
        'profile.specialization': 'Specialization',
        'profile.experience': 'Years of Experience',
        'profile.medical_history': 'Medical History (Optional)',
        'profile.update': 'Update Profile',
        'profile.language_preference': 'Language Preference',
        'profile.select_language': 'Select your preferred language',
        
        // Translation
        'translate.title': 'Medical Translation',
        'translate.subtitle': 'Break language barriers in healthcare communication',
        'translate.input_text': 'Text to Translate',
        'translate.target_language': 'Target Language',
        'translate.voice_input': 'Voice Input',
        'translate.speak_result': 'Play Audio',
        'translate.medical_terms': 'Medical Terms Found',
        'translate.no_terms': 'No medical terms detected',
        
        // ChatBot
        'chatbot.title': 'Medical Assistant',
        'chatbot.subtitle': 'Your personal health companion',
        'chatbot.chat_language': 'Chat Language',
        'chatbot.ask_question': 'Ask me about your health...',
        'chatbot.send': 'Send',
        'chatbot.medicine_tracker': 'Medicine Tracker',
        'chatbot.routine_tracker': 'Routine Tracker',
        'chatbot.add_medicine': 'Add Medicine',
        'chatbot.add_routine': 'Add Routine',
        
        // Doctor Tips
        'tips.title': 'Medical Tips & Advice',
        'tips.subtitle': 'Expert medical advice from healthcare professionals',
        'tips.add_tip': 'Add New Tip',
        'tips.tip_title': 'Tip Title',
        'tips.tip_content': 'Tip Content',
        'tips.category': 'Category',
        'tips.submit': 'Submit Tip',
        'tips.no_tips': 'No tips available yet',
        'tips.by_doctor': 'By Dr.',
        'tips.specialization': 'Specialization',
        'tips.experience': 'Experience',
        'tips.published': 'Published',
        
        // Categories
        'category.general': 'General Health',
        'category.emergency': 'Emergency Care',
        'category.medication': 'Medication',
        'category.nutrition': 'Nutrition',
        'category.exercise': 'Exercise',
        'category.mental_health': 'Mental Health',
        'category.pediatrics': 'Pediatrics',
        'category.geriatrics': 'Geriatrics',
        'category.women_health': 'Women\'s Health',
        'category.men_health': 'Men\'s Health',
        
        // Home Page
        'home.title': 'MediLingo',
        'home.subtitle': 'Breaking language barriers in healthcare conversations between doctors and patients',
        'home.get_started': 'Get Started',
        'home.try_demo': 'Try Demo',
        'home.features_title': 'Key Features',
        'home.feature_translation': 'Real-time Medical Translation',
        'home.feature_translation_desc': 'Instant translation of medical conversations in over 12 languages',
        'home.feature_medical_terms': 'Medical Term Detection',
        'home.feature_medical_terms_desc': 'AI-powered detection with easy-to-understand explanations',
        'home.feature_voice': 'Voice Integration',
        'home.feature_voice_desc': 'Speech-to-text and text-to-speech in multiple languages',
        'home.feature_chatbot': 'AI Health Assistant',
        'home.feature_chatbot_desc': 'Personal health companion for medical doubts and tracking',
        'home.feature_secure': 'Secure & Private',
        'home.feature_secure_desc': 'HIPAA-compliant with end-to-end encryption',
        'home.feature_fast': 'Fast & Reliable',
        'home.feature_fast_desc': 'Lightning-fast with 99.9% uptime guarantee',
        'home.new_features': 'New Features',
        'home.quick_speech': 'Quick Speech Widget',
        'home.quick_speech_desc': 'Get instant pronunciation of any text with our floating quick speech widget. Perfect for learning correct pronunciation of medical terms.',
        'home.try_quick_speech': 'Try Quick Speech',
        'home.language_learning': 'Language Learning',
        'home.language_learning_desc': 'Interactive medical terminology learning with quizzes and flashcards to improve your healthcare communication skills.',
        'home.try_learning': 'Try Learning',
        'home.why_choose': 'Why Choose MediLingo?',
        'home.why_accurate': 'Accurate Medical Translation',
        'home.why_accurate_desc': 'Specialized medical terminology translation with context-aware accuracy',
        'home.why_multilingual': 'Multi-language Support',
        'home.why_multilingual_desc': 'Support for 12+ languages including Hindi, Tamil, and regional dialects',
        'home.why_ai_powered': 'AI-Powered Features',
        'home.why_ai_powered_desc': 'Advanced AI for medical term detection and health assistance',
        'home.why_secure': 'Privacy First',
        'home.why_secure_desc': 'Your medical data is protected with enterprise-grade security',
        'home.why_easy': 'Easy to Use',
        'home.why_easy_desc': 'Intuitive interface designed for healthcare professionals and patients',
        'home.why_affordable': 'Affordable Solution',
        'home.why_affordable_desc': 'Cost-effective translation solution for healthcare organizations',
        
        // About Page
        'about.title': 'About MediLingo',
        'about.subtitle': 'Breaking down language barriers in healthcare to ensure every patient receives the care they deserve, regardless of their native language.',
        'about.mission': 'Our Mission',
        'about.mission_desc': 'To revolutionize healthcare communication by providing instant, accurate medical translation services that bridge language gaps between healthcare providers and patients, ensuring no one is left behind due to language barriers.',
        'about.what_we_do': 'What We Do',
        'about.real_time_translation': 'Real-time Translation',
        'about.real_time_translation_desc': 'Instant translation of medical conversations between doctors and patients in over 12 languages, ensuring clear communication during critical healthcare moments.',
        'about.medical_explanation': 'Medical Term Explanation',
        'about.medical_explanation_desc': 'Advanced AI-powered medical terminology detection with layman explanations, helping patients understand complex medical terms in their native language.',
        'about.voice_integration': 'Voice Integration',
        'about.voice_integration_desc': 'Speech-to-text and text-to-speech capabilities in multiple languages, making healthcare communication accessible for patients with different abilities.',
        'about.health_assistant': 'Personal Health Assistant',
        'about.health_assistant_desc': 'AI-powered chatbot that helps patients with medical doubts, medicine tracking, and health routine management in their preferred language.',
        'about.secure_private': 'Secure & Private',
        'about.secure_private_desc': 'HIPAA-compliant platform with end-to-end encryption, ensuring patient data privacy and security in all medical communications.',
        'about.fast_reliable': 'Fast & Reliable',
        'about.fast_reliable_desc': 'Lightning-fast translation with 99.9% uptime, ensuring healthcare providers can rely on our service during critical medical situations.',
        'about.how_it_works': 'How It Works',
        'about.step1': 'Input Text',
        'about.step1_desc': 'Enter medical text or use voice input in any supported language',
        'about.step2': 'AI Processing',
        'about.step2_desc': 'Our AI detects medical terms and translates content accurately',
        'about.step3': 'Smart Explanation',
        'about.step3_desc': 'Medical terms are highlighted with easy-to-understand explanations',
        'about.step4': 'Clear Communication',
        'about.step4_desc': 'Both parties understand each other perfectly in their preferred language',
        'about.impact': 'Our Impact',
        'about.translations_completed': 'Translations Completed',
        'about.languages_supported': 'Languages Supported',
        'about.healthcare_providers': 'Healthcare Providers',
        'about.vision': 'Our Vision',
        'about.vision_desc': 'We envision a world where language is never a barrier to receiving quality healthcare. Our goal is to make medical communication seamless, accurate, and accessible to everyone, regardless of their linguistic background. Through continuous innovation and AI advancement, we\'re building the future of inclusive healthcare communication.',
        'about.ready_to_transform': 'Ready to Transform Healthcare Communication?',
        'about.ready_desc': 'Join thousands of healthcare providers who are already using MediLingo to break down language barriers and provide better care to their patients.',
        'about.get_started_free': 'Get Started Free',
        'about.try_demo': 'Try Demo'
      },
      hi: {
        // Navigation
        'nav.home': 'होम',
        'nav.translate': 'अनुवाद',
        'nav.chatbot': 'चैटबॉट',
        'nav.history': 'इतिहास',
        'nav.profile': 'प्रोफ़ाइल',
        'nav.about': 'के बारे में',
        'nav.doctor_tips': 'डॉक्टर सुझाव',
        'nav.login': 'लॉगिन',
        'nav.signup': 'साइन अप',
        'nav.logout': 'लॉगआउट',
        
        // Authentication
        'auth.login_to_account': 'अपने खाते में लॉगिन करें',
        'auth.or': 'या',
        'auth.already_have_account': 'पहले से खाता है?',
        'auth.sign_in_here': 'यहाँ साइन इन करें',
        'auth.username': 'उपयोगकर्ता नाम',
        'auth.email': 'ईमेल पता',
        'auth.password': 'पासवर्ड',
        'auth.confirm_password': 'पासवर्ड की पुष्टि करें',
        'auth.username_placeholder': 'उपयोगकर्ता नाम चुनें',
        'auth.email_placeholder': 'अपना ईमेल दर्ज करें',
        'auth.password_placeholder': 'अपना पासवर्ड दर्ज करें',
        'auth.confirm_password_placeholder': 'अपने पासवर्ड की पुष्टि करें',
        'auth.signing_in': 'साइन इन हो रहे हैं...',
        'auth.sign_in': 'साइन इन',
        'auth.creating_account': 'खाता बनाया जा रहा है...',
        'auth.create_account': 'खाता बनाएं',
        'auth.back_to_home': '← होम पर वापस जाएं',
        
        // Common
        'common.loading': 'लोड हो रहा है...',
        'common.error': 'त्रुटि',
        'common.success': 'सफलता',
        'common.save': 'सहेजें',
        'common.cancel': 'रद्द करें',
        'common.delete': 'हटाएं',
        'common.edit': 'संपादित करें',
        'common.close': 'बंद करें',
        'common.confirm': 'पुष्टि करें',
        'common.language': 'भाषा',
        'common.speak': 'बोलें',
        'common.stop': 'रोकें',
        'common.translate': 'अनुवाद करें',
        'common.clear': 'साफ़ करें',
        
        // Profile
        'profile.title': 'प्रोफ़ाइल सेटिंग्स',
        'profile.subtitle': 'अपना खाता और भूमिका प्राथमिकताएं प्रबंधित करें',
        'profile.username': 'उपयोगकर्ता नाम',
        'profile.email': 'ईमेल',
        'profile.role_patient': 'रोगी',
        'profile.role_doctor': 'डॉक्टर',
        'profile.specialization': 'विशेषज्ञता',
        'profile.experience': 'वर्षों का अनुभव',
        'profile.medical_history': 'चिकित्सा इतिहास (वैकल्पिक)',
        'profile.update': 'प्रोफ़ाइल अपडेट करें',
        'profile.language_preference': 'भाषा प्राथमिकता',
        'profile.select_language': 'अपनी पसंदीदा भाषा चुनें',
        
        // Translation
        'translate.title': 'चिकित्सा अनुवाद',
        'translate.subtitle': 'स्वास्थ्य सेवा संचार में भाषा की बाधाओं को तोड़ें',
        'translate.input_text': 'अनुवाद के लिए पाठ',
        'translate.target_language': 'लक्ष्य भाषा',
        'translate.voice_input': 'आवाज़ इनपुट',
        'translate.speak_result': 'ऑडियो चलाएं',
        'translate.medical_terms': 'चिकित्सा शब्द मिले',
        'translate.no_terms': 'कोई चिकित्सा शब्द नहीं मिला',
        
        // ChatBot
        'chatbot.title': 'चिकित्सा सहायक',
        'chatbot.subtitle': 'आपका व्यक्तिगत स्वास्थ्य साथी',
        'chatbot.chat_language': 'चैट भाषा',
        'chatbot.ask_question': 'अपने स्वास्थ्य के बारे में पूछें...',
        'chatbot.send': 'भेजें',
        'chatbot.medicine_tracker': 'दवा ट्रैकर',
        'chatbot.routine_tracker': 'दिनचर्या ट्रैकर',
        'chatbot.add_medicine': 'दवा जोड़ें',
        'chatbot.add_routine': 'दिनचर्या जोड़ें',
        
        // Doctor Tips
        'tips.title': 'चिकित्सा सुझाव और सलाह',
        'tips.subtitle': 'स्वास्थ्य पेशेवरों से विशेषज्ञ चिकित्सा सलाह',
        'tips.add_tip': 'नया सुझाव जोड़ें',
        'tips.tip_title': 'सुझाव शीर्षक',
        'tips.tip_content': 'सुझाव सामग्री',
        'tips.category': 'श्रेणी',
        'tips.submit': 'सुझाव सबमिट करें',
        'tips.no_tips': 'अभी तक कोई सुझाव उपलब्ध नहीं',
        'tips.by_doctor': 'डॉ. द्वारा',
        'tips.specialization': 'विशेषज्ञता',
        'tips.experience': 'अनुभव',
        'tips.published': 'प्रकाशित',
        
        // Categories
        'category.general': 'सामान्य स्वास्थ्य',
        'category.emergency': 'आपातकालीन देखभाल',
        'category.medication': 'दवा',
        'category.nutrition': 'पोषण',
        'category.exercise': 'व्यायाम',
        'category.mental_health': 'मानसिक स्वास्थ्य',
        'category.pediatrics': 'बाल रोग',
        'category.geriatrics': 'वृद्धावस्था',
        'category.women_health': 'महिला स्वास्थ्य',
        'category.men_health': 'पुरुष स्वास्थ्य',
        
        // Home Page
        'home.title': 'मेडिलिंगो',
        'home.subtitle': 'डॉक्टरों और रोगियों के बीच स्वास्थ्य सेवा वार्तालाप में भाषा की बाधाओं को तोड़ना',
        'home.get_started': 'शुरू करें',
        'home.try_demo': 'डेमो आज़माएं',
        'home.features_title': 'मुख्य विशेषताएं',
        'home.feature_translation': 'रियल-टाइम मेडिकल अनुवाद',
        'home.feature_translation_desc': '12+ भाषाओं में मेडिकल वार्तालाप का तत्काल अनुवाद',
        'home.feature_medical_terms': 'मेडिकल टर्म डिटेक्शन',
        'home.feature_medical_terms_desc': 'आसान समझने वाले स्पष्टीकरण के साथ AI-संचालित डिटेक्शन',
        'home.feature_voice': 'वॉइस इंटीग्रेशन',
        'home.feature_voice_desc': 'कई भाषाओं में स्पीच-टू-टेक्स्ट और टेक्स्ट-टू-स्पीच',
        'home.feature_chatbot': 'AI हेल्थ असिस्टेंट',
        'home.feature_chatbot_desc': 'मेडिकल संदेह और ट्रैकिंग के लिए व्यक्तिगत स्वास्थ्य साथी',
        'home.feature_secure': 'सुरक्षित और निजी',
        'home.feature_secure_desc': 'एंड-टू-एंड एन्क्रिप्शन के साथ HIPAA-अनुपालित',
        'home.feature_fast': 'तेज़ और विश्वसनीय',
        'home.feature_fast_desc': '99.9% अपटाइम गारंटी के साथ बिजली की तरह तेज़',
        'home.new_features': 'नई विशेषताएं',
        'home.quick_speech': 'क्विक स्पीच विजेट',
        'home.quick_speech_desc': 'हमारे फ्लोटिंग क्विक स्पीच विजेट के साथ किसी भी टेक्स्ट का तत्काल उच्चारण प्राप्त करें। मेडिकल टर्म्स के सही उच्चारण सीखने के लिए बिल्कुल सही।',
        'home.try_quick_speech': 'क्विक स्पीच आज़माएं',
        'home.language_learning': 'भाषा सीखना',
        'home.language_learning_desc': 'अपने स्वास्थ्य सेवा संचार कौशल में सुधार के लिए क्विज़ और फ्लैशकार्ड के साथ इंटरैक्टिव मेडिकल शब्दावली सीखना।',
        'home.try_learning': 'सीखना आज़माएं',
        'home.why_choose': 'मेडिलिंगो क्यों चुनें?',
        'home.why_accurate': 'सटीक मेडिकल अनुवाद',
        'home.why_accurate_desc': 'संदर्भ-जागरूक सटीकता के साथ विशेष मेडिकल शब्दावली अनुवाद',
        'home.why_multilingual': 'बहुभाषी समर्थन',
        'home.why_multilingual_desc': 'हिंदी, तमिल और क्षेत्रीय बोलियों सहित 12+ भाषाओं का समर्थन',
        'home.why_ai_powered': 'AI-संचालित विशेषताएं',
        'home.why_ai_powered_desc': 'मेडिकल टर्म डिटेक्शन और हेल्थ असिस्टेंस के लिए उन्नत AI',
        'home.why_secure': 'गोपनीयता पहले',
        'home.why_secure_desc': 'आपका मेडिकल डेटा एंटरप्राइज़-ग्रेड सुरक्षा के साथ सुरक्षित है',
        'home.why_easy': 'उपयोग में आसान',
        'home.why_easy_desc': 'स्वास्थ्य पेशेवरों और रोगियों के लिए डिज़ाइन किया गया सहज इंटरफेस',
        'home.why_affordable': 'सस्ता समाधान',
        'home.why_affordable_desc': 'स्वास्थ्य संगठनों के लिए लागत प्रभावी अनुवाद समाधान',
        
        // About Page
        'about.title': 'मेडिलिंगो के बारे में',
        'about.subtitle': 'स्वास्थ्य सेवा में भाषा की बाधाओं को तोड़ना ताकि हर रोगी को वह देखभाल मिले जिसके वे हकदार हैं, चाहे उनकी मातृभाषा कोई भी हो।',
        'about.mission': 'हमारा मिशन',
        'about.mission_desc': 'स्वास्थ्य सेवा संचार में क्रांति लाना ताकि तत्काल, सटीक मेडिकल अनुवाद सेवाएं प्रदान करके स्वास्थ्य सेवा प्रदाताओं और रोगियों के बीच भाषा की खाई को पाटा जा सके, यह सुनिश्चित करते हुए कि भाषा की बाधा के कारण कोई पीछे न रह जाए।',
        'about.what_we_do': 'हम क्या करते हैं',
        'about.real_time_translation': 'रियल-टाइम अनुवाद',
        'about.real_time_translation_desc': '12+ भाषाओं में डॉक्टरों और रोगियों के बीच मेडिकल वार्तालाप का तत्काल अनुवाद, महत्वपूर्ण स्वास्थ्य सेवा क्षणों के दौरान स्पष्ट संचार सुनिश्चित करना।',
        'about.medical_explanation': 'मेडिकल टर्म स्पष्टीकरण',
        'about.medical_explanation_desc': 'आम आदमी के स्पष्टीकरण के साथ उन्नत AI-संचालित मेडिकल शब्दावली डिटेक्शन, रोगियों को उनकी मातृभाषा में जटिल मेडिकल शब्दों को समझने में मदद करना।',
        'about.voice_integration': 'वॉइस इंटीग्रेशन',
        'about.voice_integration_desc': 'कई भाषाओं में स्पीच-टू-टेक्स्ट और टेक्स्ट-टू-स्पीच क्षमताएं, विभिन्न क्षमताओं वाले रोगियों के लिए स्वास्थ्य सेवा संचार को सुलभ बनाना।',
        'about.health_assistant': 'व्यक्तिगत स्वास्थ्य सहायक',
        'about.health_assistant_desc': 'AI-संचालित चैटबॉट जो रोगियों को मेडिकल संदेह, दवा ट्रैकिंग और उनकी पसंदीदा भाषा में स्वास्थ्य दिनचर्या प्रबंधन में मदद करता है।',
        'about.secure_private': 'सुरक्षित और निजी',
        'about.secure_private_desc': 'एंड-टू-एंड एन्क्रिप्शन के साथ HIPAA-अनुपालित प्लेटफॉर्म, सभी मेडिकल संचार में रोगी डेटा गोपनीयता और सुरक्षा सुनिश्चित करना।',
        'about.fast_reliable': 'तेज़ और विश्वसनीय',
        'about.fast_reliable_desc': '99.9% अपटाइम के साथ बिजली की तरह तेज़ अनुवाद, यह सुनिश्चित करते हुए कि स्वास्थ्य सेवा प्रदाता महत्वपूर्ण मेडिकल स्थितियों के दौरान हमारी सेवा पर भरोसा कर सकें।',
        'about.how_it_works': 'यह कैसे काम करता है',
        'about.step1': 'इनपुट टेक्स्ट',
        'about.step1_desc': 'किसी भी समर्थित भाषा में मेडिकल टेक्स्ट दर्ज करें या वॉइस इनपुट का उपयोग करें',
        'about.step2': 'AI प्रोसेसिंग',
        'about.step2_desc': 'हमारा AI मेडिकल टर्म्स का पता लगाता है और सामग्री का सटीक अनुवाद करता है',
        'about.step3': 'स्मार्ट स्पष्टीकरण',
        'about.step3_desc': 'मेडिकल टर्म्स को आसान समझने वाले स्पष्टीकरण के साथ हाइलाइट किया जाता है',
        'about.step4': 'स्पष्ट संचार',
        'about.step4_desc': 'दोनों पक्ष अपनी पसंदीदा भाषा में एक दूसरे को पूरी तरह समझते हैं',
        'about.impact': 'हमारा प्रभाव',
        'about.translations_completed': 'अनुवाद पूर्ण',
        'about.languages_supported': 'समर्थित भाषाएं',
        'about.healthcare_providers': 'स्वास्थ्य सेवा प्रदाता',
        'about.vision': 'हमारा दृष्टिकोण',
        'about.vision_desc': 'हम एक ऐसी दुनिया की कल्पना करते हैं जहाँ भाषा कभी भी गुणवत्तापूर्ण स्वास्थ्य सेवा प्राप्त करने में बाधा नहीं बने। हमारा लक्ष्य मेडिकल संचार को सहज, सटीक और सभी के लिए सुलभ बनाना है, चाहे उनकी भाषाई पृष्ठभूमि कोई भी हो। निरंतर नवाचार और AI प्रगति के माध्यम से, हम समावेशी स्वास्थ्य सेवा संचार का भविष्य बना रहे हैं।',
        'about.ready_to_transform': 'स्वास्थ्य सेवा संचार को बदलने के लिए तैयार हैं?',
        'about.ready_desc': 'हजारों स्वास्थ्य सेवा प्रदाताओं में शामिल हों जो पहले से ही भाषा की बाधाओं को तोड़ने और अपने रोगियों को बेहतर देखभाल प्रदान करने के लिए मेडिलिंगो का उपयोग कर रहे हैं।',
        'about.get_started_free': 'मुफ्त में शुरू करें',
        'about.try_demo': 'डेमो आज़माएं'
      },
      ta: {
        // Navigation
        'nav.home': 'முகப்பு',
        'nav.translate': 'மொழிபெயர்ப்பு',
        'nav.chatbot': 'சாட்பாட்',
        'nav.history': 'வரலாறு',
        'nav.profile': 'சுயவிவரம்',
        'nav.about': 'பற்றி',
        'nav.doctor_tips': 'மருத்துவர் குறிப்புகள்',
        'nav.login': 'உள்நுழைவு',
        'nav.signup': 'பதிவு',
        'nav.logout': 'வெளியேறு',
        
        // Authentication
        'auth.login_to_account': 'உங்கள் கணக்கில் உள்நுழையவும்',
        'auth.or': 'அல்லது',
        'auth.already_have_account': 'ஏற்கனவே கணக்கு உள்ளதா?',
        'auth.sign_in_here': 'இங்கே உள்நுழையவும்',
        'auth.username': 'பயனர் பெயர்',
        'auth.email': 'மின்னஞ்சல் முகவரி',
        'auth.password': 'கடவுச்சொல்',
        'auth.confirm_password': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
        'auth.username_placeholder': 'பயனர் பெயரைத் தேர்ந்தெடுக்கவும்',
        'auth.email_placeholder': 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
        'auth.password_placeholder': 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
        'auth.confirm_password_placeholder': 'உங்கள் கடவுச்சொல்லை உறுதிப்படுத்தவும்',
        'auth.signing_in': 'உள்நுழைகிறது...',
        'auth.sign_in': 'உள்நுழையவும்',
        'auth.creating_account': 'கணக்கு உருவாக்கப்படுகிறது...',
        'auth.create_account': 'கணக்கு உருவாக்கவும்',
        'auth.back_to_home': '← முகப்புக்குத் திரும்பவும்',
        
        // Common
        'common.loading': 'ஏற்றுகிறது...',
        'common.error': 'பிழை',
        'common.success': 'வெற்றி',
        'common.save': 'சேமி',
        'common.cancel': 'ரத்து செய்',
        'common.delete': 'நீக்கு',
        'common.edit': 'திருத்து',
        'common.close': 'மூடு',
        'common.confirm': 'உறுதிப்படுத்து',
        'common.language': 'மொழி',
        'common.speak': 'பேசு',
        'common.stop': 'நிறுத்து',
        'common.translate': 'மொழிபெயர்',
        'common.clear': 'அழி',
        
        // Profile
        'profile.title': 'சுயவிவர அமைப்புகள்',
        'profile.subtitle': 'உங்கள் கணக்கு மற்றும் பாத்திர விருப்பத்தேர்வுகளை நிர்வகிக்கவும்',
        'profile.username': 'பயனர் பெயர்',
        'profile.email': 'மின்னஞ்சல்',
        'profile.role_patient': 'நோயாளி',
        'profile.role_doctor': 'மருத்துவர்',
        'profile.specialization': 'நிபுணத்துவம்',
        'profile.experience': 'ஆண்டுகள் அனுபவம்',
        'profile.medical_history': 'மருத்துவ வரலாறு (விருப்பமானது)',
        'profile.update': 'சுயவிவரத்தை புதுப்பிக்கவும்',
        'profile.language_preference': 'மொழி விருப்பம்',
        'profile.select_language': 'உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்',
        
        // Translation
        'translate.title': 'மருத்துவ மொழிபெயர்ப்பு',
        'translate.subtitle': 'சுகாதார தொடர்புகளில் மொழி தடைகளை உடைக்கவும்',
        'translate.input_text': 'மொழிபெயர்ப்புக்கான உரை',
        'translate.target_language': 'இலக்கு மொழி',
        'translate.voice_input': 'குரல் உள்ளீடு',
        'translate.speak_result': 'ஆடியோ இயக்கு',
        'translate.medical_terms': 'மருத்துவ சொற்கள் கிடைத்தன',
        'translate.no_terms': 'மருத்துவ சொற்கள் எதுவும் கிடைக்கவில்லை',
        
        // ChatBot
        'chatbot.title': 'மருத்துவ உதவியாளர்',
        'chatbot.subtitle': 'உங்கள் தனிப்பட்ட சுகாதார துணை',
        'chatbot.chat_language': 'அரட்டை மொழி',
        'chatbot.ask_question': 'உங்கள் சுகாதாரம் பற்றி கேளுங்கள்...',
        'chatbot.send': 'அனுப்பு',
        'chatbot.medicine_tracker': 'மருந்து கண்காணிப்பு',
        'chatbot.routine_tracker': 'வழக்கமான கண்காணிப்பு',
        'chatbot.add_medicine': 'மருந்து சேர்',
        'chatbot.add_routine': 'வழக்கத்தை சேர்',
        
        // Doctor Tips
        'tips.title': 'மருத்துவ குறிப்புகள் மற்றும் ஆலோசனை',
        'tips.subtitle': 'சுகாதார நிபுணர்களிடமிருந்து நிபுணர் மருத்துவ ஆலோசனை',
        'tips.add_tip': 'புதிய குறிப்பு சேர்',
        'tips.tip_title': 'குறிப்பு தலைப்பு',
        'tips.tip_content': 'குறிப்பு உள்ளடக்கம்',
        'tips.category': 'வகை',
        'tips.submit': 'குறிப்பை சமர்ப்பி',
        'tips.no_tips': 'இன்னும் குறிப்புகள் எதுவும் இல்லை',
        'tips.by_doctor': 'டாக்டர் மூலம்',
        'tips.specialization': 'நிபுணத்துவம்',
        'tips.experience': 'அனுபவம்',
        'tips.published': 'வெளியிடப்பட்டது',
        
        // Categories
        'category.general': 'பொது சுகாதாரம்',
        'category.emergency': 'அவசரகால பராமரிப்பு',
        'category.medication': 'மருந்து',
        'category.nutrition': 'ஊட்டச்சத்து',
        'category.exercise': 'உடற்பயிற்சி',
        'category.mental_health': 'மன ஆரோக்கியம்',
        'category.pediatrics': 'குழந்தை மருத்துவம்',
        'category.geriatrics': 'முதியோர் மருத்துவம்',
        'category.women_health': 'பெண்கள் சுகாதாரம்',
        'category.men_health': 'ஆண்கள் சுகாதாரம்',
        
        // Home Page
        'home.title': 'மெடிலிங்கோ',
        'home.subtitle': 'மருத்துவர்கள் மற்றும் நோயாளிகளுக்கு இடையேயான சுகாதார உரையாடல்களில் மொழி தடைகளை உடைத்தல்',
        'home.get_started': 'தொடங்குங்கள்',
        'home.try_demo': 'டெமோ முயற்சிக்கவும்',
        'home.features_title': 'முக்கிய அம்சங்கள்',
        'home.feature_translation': 'நிகழ்நேர மருத்துவ மொழிபெயர்ப்பு',
        'home.feature_translation_desc': '12+ மொழிகளில் மருத்துவ உரையாடல்களின் உடனடி மொழிபெயர்ப்பு',
        'home.feature_medical_terms': 'மருத்துவ சொல் கண்டறிதல்',
        'home.feature_medical_terms_desc': 'எளிதாக புரிந்துகொள்ளக்கூடிய விளக்கங்களுடன் AI-இயக்கப்பட்ட கண்டறிதல்',
        'home.feature_voice': 'குரல் ஒருங்கிணைப்பு',
        'home.feature_voice_desc': 'பல மொழிகளில் பேச்சு-க்கு-உரை மற்றும் உரை-க்கு-பேச்சு',
        'home.feature_chatbot': 'AI சுகாதார உதவியாளர்',
        'home.feature_chatbot_desc': 'மருத்துவ சந்தேகங்கள் மற்றும் கண்காணிப்புக்கான தனிப்பட்ட சுகாதார துணை',
        'home.feature_secure': 'பாதுகாப்பான மற்றும் தனியார்',
        'home.feature_secure_desc': 'முழு-க்கு-முழு குறியாக்கத்துடன் HIPAA-இணக்கமான',
        'home.feature_fast': 'வேகமான மற்றும் நம்பகமான',
        'home.feature_fast_desc': '99.9% செயல்பாட்டு நேரத்துடன் மின்னல் வேகம்',
        'home.new_features': 'புதிய அம்சங்கள்',
        'home.quick_speech': 'விரைவு பேச்சு விட்ஜெட்',
        'home.quick_speech_desc': 'எந்தவொரு உரையின் உடனடி உச்சரிப்பை எங்கள் மிதக்கும் விரைவு பேச்சு விட்ஜெட்டுடன் பெறுங்கள். மருத்துவ சொற்களின் சரியான உச்சரிப்பைக் கற்றுக்கொள்வதற்கு சரியானது.',
        'home.try_quick_speech': 'விரைவு பேச்சை முயற்சிக்கவும்',
        'home.language_learning': 'மொழி கற்றல்',
        'home.language_learning_desc': 'உங்கள் சுகாதார தொடர்பு திறன்களை மேம்படுத்துவதற்காக வினாடி வினாக்கள் மற்றும் ஃபிளாஷ் கார்டுகளுடன் ஊடாடும் மருத்துவ சொற்களஞ்சிய கற்றல்.',
        'home.try_learning': 'கற்றலை முயற்சிக்கவும்',
        'home.why_choose': 'மெடிலிங்கோவை ஏன் தேர்ந்தெடுக்க வேண்டும்?',
        'home.why_accurate': 'துல்லியமான மருத்துவ மொழிபெயர்ப்பு',
        'home.why_accurate_desc': 'சூழல்-விழிப்புடைய துல்லியத்துடன் சிறப்பு மருத்துவ சொற்களஞ்சிய மொழிபெயர்ப்பு',
        'home.why_multilingual': 'பல மொழி ஆதரவு',
        'home.why_multilingual_desc': 'இந்தி, தமிழ் மற்றும் பிராந்திய பேச்சுவழிகளுடன் 12+ மொழிகளுக்கு ஆதரவு',
        'home.why_ai_powered': 'AI-இயக்கப்பட்ட அம்சங்கள்',
        'home.why_ai_powered_desc': 'மருத்துவ சொல் கண்டறிதல் மற்றும் சுகாதார உதவிக்கான மேம்பட்ட AI',
        'home.why_secure': 'தனியுரிமை முதலில்',
        'home.why_secure_desc': 'உங்கள் மருத்துவ தரவு நிறுவன-தர பாதுகாப்புடன் பாதுகாக்கப்படுகிறது',
        'home.why_easy': 'பயன்படுத்த எளிதானது',
        'home.why_easy_desc': 'சுகாதார நிபுணர்கள் மற்றும் நோயாளிகளுக்காக வடிவமைக்கப்பட்ட உள்ளுணர்வு இடைமுகம்',
        'home.why_affordable': 'மலிவான தீர்வு',
        'home.why_affordable_desc': 'சுகாதார அமைப்புகளுக்கான செலவு-பயனுள்ள மொழிபெயர்ப்பு தீர்வு',
        
        // About Page
        'about.title': 'மெடிலிங்கோ பற்றி',
        'about.subtitle': 'ஒவ்வொரு நோயாளியும் தங்கள் மொழியைப் பொருட்படுத்தாமல் தகுதியான பராமரிப்பைப் பெறுவதை உறுதிப்படுத்த சுகாதாரத்தில் மொழி தடைகளை உடைத்தல்.',
        'about.mission': 'எங்கள் பணி',
        'about.mission_desc': 'மொழி தடைகளால் யாரும் பின்தங்காமல் இருக்கும்படி உறுதிப்படுத்தி, சுகாதார வழங்குநர்கள் மற்றும் நோயாளிகளுக்கு இடையேயான மொழி இடைவெளிகளை இணைக்கும் உடனடி, துல்லியமான மருத்துவ மொழிபெயர்ப்பு சேவைகளை வழங்குவதன் மூலம் சுகாதார தொடர்பில் புரட்சியை ஏற்படுத்துதல்.',
        'about.what_we_do': 'நாங்கள் என்ன செய்கிறோம்',
        'about.real_time_translation': 'நிகழ்நேர மொழிபெயர்ப்பு',
        'about.real_time_translation_desc': '12+ மொழிகளில் மருத்துவர்கள் மற்றும் நோயாளிகளுக்கு இடையேயான மருத்துவ உரையாடல்களின் உடனடி மொழிபெயர்ப்பு, முக்கியமான சுகாதார தருணங்களில் தெளிவான தொடர்பை உறுதிப்படுத்துதல்.',
        'about.medical_explanation': 'மருத்துவ சொல் விளக்கம்',
        'about.medical_explanation_desc': 'மேம்பட்ட AI-இயக்கப்பட்ட மருத்துவ சொற்களஞ்சிய கண்டறிதல் சாதாரண மனிதன் விளக்கங்களுடன், நோயாளிகள் தங்கள் தாய்மொழியில் சிக்கலான மருத்துவ சொற்களை புரிந்துகொள்ள உதவுதல்.',
        'about.voice_integration': 'குரல் ஒருங்கிணைப்பு',
        'about.voice_integration_desc': 'பல மொழிகளில் பேச்சு-க்கு-உரை மற்றும் உரை-க்கு-பேச்சு திறன்கள், வெவ்வேறு திறன்களைக் கொண்ட நோயாளிகளுக்கு சுகாதார தொடர்பை அணுகக்கூடியதாக்குதல்.',
        'about.health_assistant': 'தனிப்பட்ட சுகாதார உதவியாளர்',
        'about.health_assistant_desc': 'மருத்துவ சந்தேகங்கள், மருந்து கண்காணிப்பு மற்றும் தங்கள் விருப்பமான மொழியில் சுகாதார வழக்கத்தை நிர்வகிப்பதில் நோயாளிகளுக்கு உதவும் AI-இயக்கப்பட்ட சாட்பாட்.',
        'about.secure_private': 'பாதுகாப்பான மற்றும் தனியார்',
        'about.secure_private_desc': 'முழு-க்கு-முழு குறியாக்கத்துடன் HIPAA-இணக்கமான தளம், அனைத்து மருத்துவ தொடர்புகளிலும் நோயாளி தரவு தனியுரிமை மற்றும் பாதுகாப்பை உறுதிப்படுத்துதல்.',
        'about.fast_reliable': 'வேகமான மற்றும் நம்பகமான',
        'about.fast_reliable_desc': '99.9% செயல்பாட்டு நேரத்துடன் மின்னல் வேக மொழிபெயர்ப்பு, முக்கியமான மருத்துவ சூழ்நிலைகளில் சுகாதார வழங்குநர்கள் எங்கள் சேவையை நம்பலாம் என்பதை உறுதிப்படுத்துதல்.',
        'about.how_it_works': 'இது எப்படி வேலை செய்கிறது',
        'about.step1': 'உள்ளீடு உரை',
        'about.step1_desc': 'எந்தவொரு ஆதரவு மொழியிலும் மருத்துவ உரையை உள்ளிடவும் அல்லது குரல் உள்ளீட்டைப் பயன்படுத்தவும்',
        'about.step2': 'AI செயலாக்கம்',
        'about.step2_desc': 'எங்கள் AI மருத்துவ சொற்களைக் கண்டறிந்து உள்ளடக்கத்தை துல்லியமாக மொழிபெயர்க்கிறது',
        'about.step3': 'ஸ்மார்ட் விளக்கம்',
        'about.step3_desc': 'மருத்துவ சொற்கள் எளிதாக புரிந்துகொள்ளக்கூடிய விளக்கங்களுடன் முன்னிலைப்படுத்தப்படுகின்றன',
        'about.step4': 'தெளிவான தொடர்பு',
        'about.step4_desc': 'இரண்டு தரப்பினரும் தங்கள் விருப்பமான மொழியில் ஒருவரையொருவர் சரியாக புரிந்துகொள்கிறார்கள்',
        'about.impact': 'எங்கள் தாக்கம்',
        'about.translations_completed': 'மொழிபெயர்ப்புகள் முடிந்தது',
        'about.languages_supported': 'ஆதரவு மொழிகள்',
        'about.healthcare_providers': 'சுகாதார வழங்குநர்கள்',
        'about.vision': 'எங்கள் பார்வை',
        'about.vision_desc': 'மொழி ஒருபோதும் தரமான சுகாதார சேவையைப் பெறுவதற்கு தடையாக இருக்காத உலகத்தை நாங்கள் கற்பனை செய்கிறோம். மொழியியல் பின்னணியைப் பொருட்படுத்தாமல், அனைவருக்கும் மருத்துவ தொடர்பை இணைப்பற்ற, துல்லியமான மற்றும் அணுகக்கூடியதாக மாற்றுவதே எங்கள் குறிக்கோள். தொடர்ச்சியான கண்டுபிடிப்பு மற்றும் AI முன்னேற்றத்தின் மூலம், நாங்கள் உள்ளடக்கிய சுகாதார தொடர்பின் எதிர்காலத்தை உருவாக்குகிறோம்.',
        'about.ready_to_transform': 'சுகாதார தொடர்பை மாற்ற தயாரா?',
        'about.ready_desc': 'மொழி தடைகளை உடைத்து தங்கள் நோயாளிகளுக்கு சிறந்த பராமரிப்பை வழங்க மெடிலிங்கோவை ஏற்கனவே பயன்படுத்தும் ஆயிரக்கணக்கான சுகாதார வழங்குநர்களுடன் சேரவும்.',
        'about.get_started_free': 'இலவசமாக தொடங்குங்கள்',
        'about.try_demo': 'டெமோ முயற்சிக்கவும்'
      }
    };

    return translations[currentLanguage]?.[key] || key;
  };

  const value = {
    currentLanguage,
    languages,
    changeLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
